language: ruby
rvm:
  - 2.4.2

before_install:
  - openssl aes-256-cbc -K $encrypted_9c4f88871076_key -iv $encrypted_9c4f88871076_iv -in .travis_rsa.enc -out .travis_rsa -d
  - cp .travis_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: ./script/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GIT_COMMITTER_NAME=miyohide
    - GIT_COMMITTER_EMAIL=miyohide@gmail.com
    - GIT_AUTHOR_NAME=miyohide
    - GIT_AUTHOR_EMAIL=miyohide@gmail.com

sudo: false

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./script/create_pull_request.sh

