title: Rubyist Magazine
email: magazine@ruby-no-kai.org
description: > # this means to ignore newlines until "baseurl:"
  『Rubyist Magazine』、略して『るびま』は、
  Rubyist の Rubyist による、Rubyist とそうでない人のためのウェブ雑誌です。
baseurl: ""
url: "https://magazine.rubyist.net" # the base hostname & protocol for your site

permalink: none

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  autolink: true

exclude: ["Gemfile", "Gemfile.lock", "tools", "tmp", "script", "README.md", "hiki_docs", "vendor"]
